/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArticleTextHighlighter: (typeof import("./pdf/ArticleTextHighlighter.vue"))["default"]
    BarChart: typeof import('./components/charts/BarChart.vue')['default']
    CarsInfo: typeof import('./pages/dashboard/overview/components/CarsInfo.vue')['default']
    Deities: typeof import('./components/deities.vue')['default']
    FeatureCard: typeof import('./pages/home/components/Features/FeatureCard.vue')['default']
    Features: typeof import('./pages/home/components/Features/index.vue')['default']
    Hero: typeof import('./pages/home/components/hero/Hero.vue')['default']
    LineChart: typeof import('./components/charts/LineChart.vue')['default']
    LocaleToggler: typeof import('./components/blocks/LocaleToggler.vue')['default']
    Logo: typeof import('./components/blocks/Logo.vue')['default']
    Mcqs: typeof import('./components/polls/mcqs.vue')['default']
    Open: typeof import('./components/polls/open.vue')['default']
    PieChart: typeof import('./components/charts/PieChart.vue')['default']
    Ranked: typeof import('./components/polls/ranked.vue')['default']
    RankedPriority: typeof import('./components/survey-1/RankedPriority.vue')['default']
    Ratings: typeof import('./components/polls/ratings.vue')['default']
    RentalByType: typeof import('./pages/dashboard/overview/components/RentalByType.vue')['default']
    RentalFrequency: typeof import('./pages/dashboard/overview/components/RentalFrequency.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./components/blocks/Settings.vue')['default']
    StatCardOverview: typeof import('./pages/dashboard/overview/components/StatCardOverview.vue')['default']
    SurveyQuestions: typeof import('./components/survey-1/SurveyQuestions.vue')['default']
    Tf: typeof import('./components/polls/tf.vue')['default']
    ThemeToggler: typeof import('./components/blocks/ThemeToggler.vue')['default']
    ToggleDirection: typeof import('./components/blocks/ToggleDirection.vue')['default']
  }
}
