/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddNewInvoice: typeof import('./components/dialogs/AddNewInvoice.vue')['default']
    AddNewPatient: typeof import('./components/dialogs/AddNewPatient.vue')['default']
    AddNewVisit: typeof import('./components/dialogs/AddNewVisit.vue')['default']
    AddStaffMember: typeof import('./components/dialogs/AddStaffMember.vue')['default']
    Admin: typeof import('./components/admin/index.vue')['default']
    Administrative: typeof import('./pages/dashboard/services/components/Administrative.vue')['default']
    AmendInvoiceDialog: typeof import('./components/dialogs/AmendInvoiceDialog.vue')['default']
    CashOffice: typeof import('./pages/dashboard/services/components/CashOffice.vue')['default']
    Clinical: typeof import('./pages/dashboard/services/components/Clinical.vue')['default']
    CommonAlerts: typeof import('./components/alerts/CommonAlerts.vue')['default']
    ConfirmCloseVisit: typeof import('./components/dialogs/ConfirmCloseVisit.vue')['default']
    CreateNewDocumentation: typeof import('./components/dialogs/CreateNewDocumentation.vue')['default']
    CreateReport: typeof import('./components/dialogs/WriteServiceReport.vue')['default']
    Credits: typeof import('./components/payments/credits.vue')['default']
    FeatureCard: typeof import('./pages/welcome/components/Features/FeatureCard.vue')['default']
    Features: typeof import('./pages/welcome/components/Features/index.vue')['default']
    FeeWaiver: typeof import('./components/payments/FeeWaiver.vue')['default']
    Hero: typeof import('./pages/welcome/components/hero/Hero.vue')['default']
    Insurance: typeof import('./components/payments/insurance.vue')['default']
    Laboratory: typeof import('./pages/dashboard/services/components/Laboratory.vue')['default']
    LocaleToggler: typeof import('./components/blocks/LocaleToggler.vue')['default']
    Logo: typeof import('./components/blocks/Logo.vue')['default']
    MPESABillPayment: typeof import('./components/payments/MPESABillPayment.vue')['default']
    MpesaDonation: typeof import('./components/payments/mpesaDonation.vue')['default']
    NewServicesRequest: typeof import('./components/dialogs/NewServicesRequest.vue')['default']
    NoSearchMatch: typeof import('./components/dialogs/NoSearchMatch.vue')['default']
    Nursing: typeof import('./pages/dashboard/services/components/Nursing.vue')['default']
    PaymentEntry: typeof import('./components/payments/paymentEntry.vue')['default']
    PaymentsManagementTable: typeof import('./components/admin/Components/PaymentsManagementTable.vue')['default']
    Paypal: typeof import('./components/payments/paypal.vue')['default']
    Privacy: typeof import('./components/termsAndConditions/privacy.vue')['default']
    Records: typeof import('./pages/dashboard/services/components/Records.vue')['default']
    ResourceManagementTable: typeof import('./components/admin/Components/ResourceManagementTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./components/blocks/Settings.vue')['default']
    Terminal: typeof import('./pages/terminal/components/Terminal.vue')['default']
    Terms: typeof import('./components/termsAndConditions/terms.vue')['default']
    ThemeToggler: typeof import('./components/blocks/ThemeToggler.vue')['default']
    ToggleDirection: typeof import('./components/blocks/ToggleDirection.vue')['default']
    UserManagementTable: typeof import('./components/admin/Components/UserManagementTable.vue')['default']
    ViewPatientRecords: typeof import('./components/dialogs/ViewPatientRecords.vue')['default']
    ViewServicesReports: typeof import('./components/dialogs/ViewServicesReports.vue')['default']
    WritePatientNotes: typeof import('./components/dialogs/WritePatientNotes.vue')['default']
    WriteServiceReport: typeof import('./components/dialogs/WriteServiceReport.vue')['default']
  }
}
